server:
  port: 8081
spring:
  application:
    name: koala-rs
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123123
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
