server:
  port: 8080
spring:
  application:
    name: koala-uaa
  datasource:
    url: jdbc:mysql://localhost:3306/koalauaa?zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&autoReconnectForPools=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123123
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml